package model.Cutting_ManPower.AM.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 12 17:31:03 PKT 2018
// ---------------------------------------------------------------------
public interface Cutting_ManPower_AM extends ApplicationModule {
    void setSessionValues(String orgId, String userId, String respId,
                          String respAppl);

    void Populate();

    void TotalProducedMins_Calc();

    void save();

    void CodeDescPopulate();
}
