package model.Cutting_ManPower.EO;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 12 14:38:58 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCuttingWorkingHoursH_EOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        },
        OrgId {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        },
        OrganizationId {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getOrganizationId();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setOrganizationId((Number)value);
            }
        },
        DocumentNo {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getDocumentNo();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setDocumentNo((String)value);
            }
        },
        DocumentDate {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getDocumentDate();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setDocumentDate((Date)value);
            }
        },
        DocumentType {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getDocumentType();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setDocumentType((String)value);
            }
        },
        TotalProduction {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getTotalProduction();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setTotalProduction((Number)value);
            }
        },
        TotalProducedMinutes {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getTotalProducedMinutes();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setTotalProducedMinutes((Number)value);
            }
        },
        TotalAttendedMinutes {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getTotalAttendedMinutes();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setTotalAttendedMinutes((Number)value);
            }
        },
        Efficiency {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getEfficiency();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setEfficiency((Number)value);
            }
        },
        Remarks {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        },
        VersionNumber {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        },
        VersionDate {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        },
        Status {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getStatus();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        },
        Enabled {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getEnabled();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setEnabled((String)value);
            }
        },
        CreatedBy {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        },
        CreationDate {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        LastUpdatedBy {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        },
        LastUpdateDate {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        },
        LastUpdateLogin {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        },
        Attribute1 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        },
        Attribute2 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        },
        Attribute3 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        },
        Attribute4 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        },
        Attribute5 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        },
        Attribute6 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        },
        Attribute7 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        },
        Attribute8 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        },
        Attribute9 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        },
        Attribute10 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        },
        Attribute11 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        },
        Attribute12 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        },
        Attribute13 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        },
        Attribute14 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        },
        Attribute15 {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        },
        OperatingUnit {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getOperatingUnit();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setOperatingUnit((String)value);
            }
        },
        MnjCuttingWorkingHoursProd_EO {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getMnjCuttingWorkingHoursProd_EO();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        MnjCuttingWorkingHoursL_EO {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getMnjCuttingWorkingHoursL_EO();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        },
        MnjCuttingOffStandardL_EO {
            public Object get(MnjCuttingWorkingHoursH_EOImpl obj) {
                return obj.getMnjCuttingOffStandardL_EO();
            }

            public void put(MnjCuttingWorkingHoursH_EOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjCuttingWorkingHoursH_EOImpl object);

        public abstract void put(MnjCuttingWorkingHoursH_EOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ORGANIZATIONID =
        AttributesEnum.OrganizationId.index();
    public static final int DOCUMENTNO = AttributesEnum.DocumentNo.index();
    public static final int DOCUMENTDATE = AttributesEnum.DocumentDate.index();
    public static final int DOCUMENTTYPE = AttributesEnum.DocumentType.index();
    public static final int TOTALPRODUCTION =
        AttributesEnum.TotalProduction.index();
    public static final int TOTALPRODUCEDMINUTES =
        AttributesEnum.TotalProducedMinutes.index();
    public static final int TOTALATTENDEDMINUTES =
        AttributesEnum.TotalAttendedMinutes.index();
    public static final int EFFICIENCY = AttributesEnum.Efficiency.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int VERSIONNUMBER =
        AttributesEnum.VersionNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int ENABLED = AttributesEnum.Enabled.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE =
        AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN =
        AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int OPERATINGUNIT =
        AttributesEnum.OperatingUnit.index();
    public static final int MNJCUTTINGWORKINGHOURSPROD_EO =
        AttributesEnum.MnjCuttingWorkingHoursProd_EO.index();
    public static final int MNJCUTTINGWORKINGHOURSL_EO =
        AttributesEnum.MnjCuttingWorkingHoursL_EO.index();
    public static final int MNJCUTTINGOFFSTANDARDL_EO =
        AttributesEnum.MnjCuttingOffStandardL_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjCuttingWorkingHoursH_EOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    EntityDefImpl.findDefObject("model.Cutting_ManPower.EO.MnjCuttingWorkingHoursH_EO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for OrganizationId, using the alias name OrganizationId.
     * @return the OrganizationId
     */
    public Number getOrganizationId() {
        return (Number)getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrganizationId.
     * @param value value to set the OrganizationId
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * Gets the attribute value for DocumentNo, using the alias name DocumentNo.
     * @return the DocumentNo
     */
    public String getDocumentNo() {
        return (String)getAttributeInternal(DOCUMENTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentNo.
     * @param value value to set the DocumentNo
     */
    public void setDocumentNo(String value) {
        setAttributeInternal(DOCUMENTNO, value);
    }

    /**
     * Gets the attribute value for DocumentDate, using the alias name DocumentDate.
     * @return the DocumentDate
     */
    public Date getDocumentDate() {
        return (Date)getAttributeInternal(DOCUMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentDate.
     * @param value value to set the DocumentDate
     */
    public void setDocumentDate(Date value) {
        setAttributeInternal(DOCUMENTDATE, value);
    }

    /**
     * Gets the attribute value for DocumentType, using the alias name DocumentType.
     * @return the DocumentType
     */
    public String getDocumentType() {
        return (String)getAttributeInternal(DOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentType.
     * @param value value to set the DocumentType
     */
    public void setDocumentType(String value) {
        setAttributeInternal(DOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for TotalProduction, using the alias name TotalProduction.
     * @return the TotalProduction
     */
    public Number getTotalProduction() {
        return (Number)getAttributeInternal(TOTALPRODUCTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalProduction.
     * @param value value to set the TotalProduction
     */
    public void setTotalProduction(Number value) {
        setAttributeInternal(TOTALPRODUCTION, value);
    }

    /**
     * Gets the attribute value for TotalProducedMinutes, using the alias name TotalProducedMinutes.
     * @return the TotalProducedMinutes
     */
    public Number getTotalProducedMinutes() {
        return (Number)getAttributeInternal(TOTALPRODUCEDMINUTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalProducedMinutes.
     * @param value value to set the TotalProducedMinutes
     */
    public void setTotalProducedMinutes(Number value) {
        setAttributeInternal(TOTALPRODUCEDMINUTES, value);
    }

    /**
     * Gets the attribute value for TotalAttendedMinutes, using the alias name TotalAttendedMinutes.
     * @return the TotalAttendedMinutes
     */
    public Number getTotalAttendedMinutes() {
        return (Number)getAttributeInternal(TOTALATTENDEDMINUTES);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalAttendedMinutes.
     * @param value value to set the TotalAttendedMinutes
     */
    public void setTotalAttendedMinutes(Number value) {
        setAttributeInternal(TOTALATTENDEDMINUTES, value);
    }

    /**
     * Gets the attribute value for Efficiency, using the alias name Efficiency.
     * @return the Efficiency
     */
    public Number getEfficiency() {
        return (Number)getAttributeInternal(EFFICIENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Efficiency.
     * @param value value to set the Efficiency
     */
    public void setEfficiency(Number value) {
        setAttributeInternal(EFFICIENCY, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the VersionNumber
     */
    public Number getVersionNumber() {
        return (Number)getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for Enabled, using the alias name Enabled.
     * @return the Enabled
     */
    public String getEnabled() {
        return (String)getAttributeInternal(ENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Enabled.
     * @param value value to set the Enabled
     */
    public void setEnabled(String value) {
        setAttributeInternal(ENABLED, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for OperatingUnit, using the alias name OperatingUnit.
     * @return the OperatingUnit
     */
    public String getOperatingUnit() {
        return (String)getAttributeInternal(OPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for OperatingUnit.
     * @param value value to set the OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjCuttingWorkingHoursProd_EO() {
        return (RowIterator)getAttributeInternal(MNJCUTTINGWORKINGHOURSPROD_EO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjCuttingWorkingHoursL_EO() {
        return (RowIterator)getAttributeInternal(MNJCUTTINGWORKINGHOURSL_EO);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMnjCuttingOffStandardL_EO() {
        return (RowIterator)getAttributeInternal(MNJCUTTINGOFFSTANDARDL_EO);
    }


    /**
     * @param headerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number headerId) {
        return new Key(new Object[] { headerId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_CUTTING_WORKING_HOURS_H_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setHeaderId(sVal);

        System.out.println("In Create");

        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String orgId = (String)sessionScope.get("orgId");
        String unitName = (String)sessionScope.get("unitName");

        System.out.println("Session Parameters are..." + orgId + " " +
                           unitName);
        try {
            this.setOrgId(new oracle.jbo.domain.Number(orgId));
        } catch (SQLException e) {
            ;
        }
        setOperatingUnit(unitName);

        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        System.out.println("In doDML");

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String user = (String)sessionScope.get("userId");
        String orgId = (String)sessionScope.get("orgId");
        String unitName = (String)sessionScope.get("unitName");

        System.out.println("Session Parameters are... " + user + " " + orgId +
                           " " + unitName);

        if (operation == DML_INSERT) {
            System.out.println("In Insert");
            try {
                setDocumentNo(getSrNoString());
                System.out.println("Document No -->" + getSrNoString());
                setCreationDate((Date)Date.getCurrentDate());
                setCreatedBy(new oracle.jbo.domain.Number(user));
                setLastUpdateDate((Date)Date.getCurrentDate());
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
            } catch (SQLException f) {
                ;
            }
        } else if (DML_UPDATE == operation) {
            System.out.println("In Update");
            try {
                setLastUpdateDate((Date)Date.getCurrentDate());
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
            } catch (SQLException f) {
                ;
            }
        }
        super.doDML(operation, e);
    }

    public String getSrNoString() {
        String srno = null;
        String stmt = "BEGIN :1 := MNJ_CUTTING_WORKING_HRS_DOCNO; end;";
        java.sql.CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        try {
            cs.registerOutParameter(1, oracle.jdbc.OracleTypes.VARCHAR);
            cs.execute();
            srno = cs.getString(1);
            cs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return srno;
    }
}
