package model.Cutting_ManPower.AM.client;

import model.Cutting_ManPower.AM.common.Cutting_ManPower_AM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 12 17:31:03 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Cutting_ManPower_AMClient extends ApplicationModuleImpl implements Cutting_ManPower_AM {
    /**
     * This is the default constructor (do not remove).
     */
    public Cutting_ManPower_AMClient() {
    }


    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void Populate() {
        Object _ret = this.riInvokeExportedMethod(this,"Populate",null,null);
        return;
    }

    public void TotalProducedMins_Calc() {
        Object _ret =
            this.riInvokeExportedMethod(this,"TotalProducedMins_Calc",null,null);
        return;
    }

    public void save() {
        Object _ret = this.riInvokeExportedMethod(this,"save",null,null);
        return;
    }

    public void CodeDescPopulate() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CodeDescPopulate",null,null);
        return;
    }
}
