package model.Cutting_ManPower.VO;

import model.Cutting_ManPower.EO.MnjCuttingWorkingHoursH_EOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 12 14:38:44 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCuttingWorkingHoursH_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        OrganizationId {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getOrganizationId();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setOrganizationId((Number)value);
            }
        }
        ,
        DocumentNo {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getDocumentNo();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setDocumentNo((String)value);
            }
        }
        ,
        DocumentDate {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getDocumentDate();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setDocumentDate((Date)value);
            }
        }
        ,
        DocumentType {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getDocumentType();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setDocumentType((String)value);
            }
        }
        ,
        TotalProduction {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getTotalProduction();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setTotalProduction((Number)value);
            }
        }
        ,
        TotalProducedMinutes {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getTotalProducedMinutes();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setTotalProducedMinutes((Number)value);
            }
        }
        ,
        TotalAttendedMinutes {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getTotalAttendedMinutes();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setTotalAttendedMinutes((Number)value);
            }
        }
        ,
        Efficiency {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getEfficiency();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setEfficiency((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        VersionNumber {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        Status {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getStatus();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Enabled {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getEnabled();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setEnabled((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        OperatingUnit {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getOperatingUnit();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setOperatingUnit((String)value);
            }
        }
        ,
        TotalProducedMins {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getTotalProducedMins();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setTotalProducedMins((Number)value);
            }
        }
        ,
        TotalAttendedMins {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getTotalAttendedMins();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setTotalAttendedMins((Number)value);
            }
        }
        ,
        MnjCuttingWorkingHoursProd_VO {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getMnjCuttingWorkingHoursProd_VO();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjCuttingWorkingHoursL_VO {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getMnjCuttingWorkingHoursL_VO();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MnjCuttingOffStandardL_VO {
            public Object get(MnjCuttingWorkingHoursH_VORowImpl obj) {
                return obj.getMnjCuttingOffStandardL_VO();
            }

            public void put(MnjCuttingWorkingHoursH_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjCuttingWorkingHoursH_VORowImpl object);

        public abstract void put(MnjCuttingWorkingHoursH_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();
    public static final int DOCUMENTNO = AttributesEnum.DocumentNo.index();
    public static final int DOCUMENTDATE = AttributesEnum.DocumentDate.index();
    public static final int DOCUMENTTYPE = AttributesEnum.DocumentType.index();
    public static final int TOTALPRODUCTION = AttributesEnum.TotalProduction.index();
    public static final int TOTALPRODUCEDMINUTES = AttributesEnum.TotalProducedMinutes.index();
    public static final int TOTALATTENDEDMINUTES = AttributesEnum.TotalAttendedMinutes.index();
    public static final int EFFICIENCY = AttributesEnum.Efficiency.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int ENABLED = AttributesEnum.Enabled.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int OPERATINGUNIT = AttributesEnum.OperatingUnit.index();
    public static final int TOTALPRODUCEDMINS = AttributesEnum.TotalProducedMins.index();
    public static final int TOTALATTENDEDMINS = AttributesEnum.TotalAttendedMins.index();
    public static final int MNJCUTTINGWORKINGHOURSPROD_VO = AttributesEnum.MnjCuttingWorkingHoursProd_VO.index();
    public static final int MNJCUTTINGWORKINGHOURSL_VO = AttributesEnum.MnjCuttingWorkingHoursL_VO.index();
    public static final int MNJCUTTINGOFFSTANDARDL_VO = AttributesEnum.MnjCuttingOffStandardL_VO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjCuttingWorkingHoursH_VORowImpl() {
    }

    /**
     * Gets MnjCuttingWorkingHoursH_EO entity object.
     * @return the MnjCuttingWorkingHoursH_EO
     */
    public MnjCuttingWorkingHoursH_EOImpl getMnjCuttingWorkingHoursH_EO() {
        return (MnjCuttingWorkingHoursH_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @return the ORGANIZATION_ID
     */
    public Number getOrganizationId() {
        return (Number) getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @param value value to set the ORGANIZATION_ID
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_NO using the alias name DocumentNo.
     * @return the DOCUMENT_NO
     */
    public String getDocumentNo() {
        return (String) getAttributeInternal(DOCUMENTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_NO using the alias name DocumentNo.
     * @param value value to set the DOCUMENT_NO
     */
    public void setDocumentNo(String value) {
        setAttributeInternal(DOCUMENTNO, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_DATE using the alias name DocumentDate.
     * @return the DOCUMENT_DATE
     */
    public Date getDocumentDate() {
        return (Date) getAttributeInternal(DOCUMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_DATE using the alias name DocumentDate.
     * @param value value to set the DOCUMENT_DATE
     */
    public void setDocumentDate(Date value) {
        setAttributeInternal(DOCUMENTDATE, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_TYPE using the alias name DocumentType.
     * @return the DOCUMENT_TYPE
     */
    public String getDocumentType() {
        return (String) getAttributeInternal(DOCUMENTTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_TYPE using the alias name DocumentType.
     * @param value value to set the DOCUMENT_TYPE
     */
    public void setDocumentType(String value) {
        setAttributeInternal(DOCUMENTTYPE, value);
    }

    /**
     * Gets the attribute value for TOTAL_PRODUCTION using the alias name TotalProduction.
     * @return the TOTAL_PRODUCTION
     */
    public Number getTotalProduction() {
        return (Number) getAttributeInternal(TOTALPRODUCTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_PRODUCTION using the alias name TotalProduction.
     * @param value value to set the TOTAL_PRODUCTION
     */
    public void setTotalProduction(Number value) {
        setAttributeInternal(TOTALPRODUCTION, value);
    }

    /**
     * Gets the attribute value for TOTAL_PRODUCED_MINUTES using the alias name TotalProducedMinutes.
     * @return the TOTAL_PRODUCED_MINUTES
     */
    public Number getTotalProducedMinutes() {
        return (Number) getAttributeInternal(TOTALPRODUCEDMINUTES);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_PRODUCED_MINUTES using the alias name TotalProducedMinutes.
     * @param value value to set the TOTAL_PRODUCED_MINUTES
     */
    public void setTotalProducedMinutes(Number value) {
        setAttributeInternal(TOTALPRODUCEDMINUTES, value);
    }

    /**
     * Gets the attribute value for TOTAL_ATTENDED_MINUTES using the alias name TotalAttendedMinutes.
     * @return the TOTAL_ATTENDED_MINUTES
     */
    public Number getTotalAttendedMinutes() {
        return (Number) getAttributeInternal(TOTALATTENDEDMINUTES);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_ATTENDED_MINUTES using the alias name TotalAttendedMinutes.
     * @param value value to set the TOTAL_ATTENDED_MINUTES
     */
    public void setTotalAttendedMinutes(Number value) {
        setAttributeInternal(TOTALATTENDEDMINUTES, value);
    }

    /**
     * Gets the attribute value for EFFICIENCY using the alias name Efficiency.
     * @return the EFFICIENCY
     */
    public Number getEfficiency() {
        return (Number) getAttributeInternal(EFFICIENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFICIENCY using the alias name Efficiency.
     * @param value value to set the EFFICIENCY
     */
    public void setEfficiency(Number value) {
        setAttributeInternal(EFFICIENCY, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public Number getVersionNumber() {
        return (Number) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VERSION_DATE using the alias name VersionDate.
     * @return the VERSION_DATE
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_DATE using the alias name VersionDate.
     * @param value value to set the VERSION_DATE
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for ENABLED using the alias name Enabled.
     * @return the ENABLED
     */
    public String getEnabled() {
        return (String) getAttributeInternal(ENABLED);
    }

    /**
     * Sets <code>value</code> as attribute value for ENABLED using the alias name Enabled.
     * @param value value to set the ENABLED
     */
    public void setEnabled(String value) {
        setAttributeInternal(ENABLED, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OperatingUnit.
     * @return the OperatingUnit
     */
    public String getOperatingUnit() {
        return (String) getAttributeInternal(OPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit.
     * @param value value to set the  OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalProducedMins.
     * @return the TotalProducedMins
     */
    public Number getTotalProducedMins() {
        return (Number) getAttributeInternal(TOTALPRODUCEDMINS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalProducedMins.
     * @param value value to set the  TotalProducedMins
     */
    public void setTotalProducedMins(Number value) {
        setAttributeInternal(TOTALPRODUCEDMINS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalAttendedMins.
     * @return the TotalAttendedMins
     */
    public Number getTotalAttendedMins() {
        return (Number) getAttributeInternal(TOTALATTENDEDMINS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalAttendedMins.
     * @param value value to set the  TotalAttendedMins
     */
    public void setTotalAttendedMins(Number value) {
        setAttributeInternal(TOTALATTENDEDMINS, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjCuttingWorkingHoursProd_VO.
     */
    public RowIterator getMnjCuttingWorkingHoursProd_VO() {
        return (RowIterator)getAttributeInternal(MNJCUTTINGWORKINGHOURSPROD_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjCuttingWorkingHoursL_VO.
     */
    public RowIterator getMnjCuttingWorkingHoursL_VO() {
        return (RowIterator)getAttributeInternal(MNJCUTTINGWORKINGHOURSL_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MnjCuttingOffStandardL_VO.
     */
    public RowIterator getMnjCuttingOffStandardL_VO() {
        return (RowIterator)getAttributeInternal(MNJCUTTINGOFFSTANDARDL_VO);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
