package model.Cutting_ManPower.VO;

import model.Cutting_ManPower.EO.MnjCuttingWorkingHoursL_EOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 12 14:47:32 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCuttingWorkingHoursL_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LineId {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getLineId();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        OrganizationId {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getOrganizationId();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setOrganizationId((Number)value);
            }
        }
        ,
        WorkingHourBasic {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getWorkingHourBasic();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setWorkingHourBasic((Number)value);
            }
        }
        ,
        ManpowerBasic {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getManpowerBasic();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setManpowerBasic((Number)value);
            }
        }
        ,
        WorkingHourOvertime {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getWorkingHourOvertime();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setWorkingHourOvertime((Number)value);
            }
        }
        ,
        ManpowerOvertime {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getManpowerOvertime();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setManpowerOvertime((Number)value);
            }
        }
        ,
        WorkingHourExtraot1 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getWorkingHourExtraot1();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setWorkingHourExtraot1((Number)value);
            }
        }
        ,
        ManPowerExtraot1 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getManPowerExtraot1();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setManPowerExtraot1((Number)value);
            }
        }
        ,
        WorkingHourExtraot2 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getWorkingHourExtraot2();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setWorkingHourExtraot2((Number)value);
            }
        }
        ,
        ManPowerExtraot2 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getManPowerExtraot2();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setManPowerExtraot2((Number)value);
            }
        }
        ,
        TotalAttendedMinutes {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getTotalAttendedMinutes();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setTotalAttendedMinutes((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Total {
            public Object get(MnjCuttingWorkingHoursL_VORowImpl obj) {
                return obj.getTotal();
            }

            public void put(MnjCuttingWorkingHoursL_VORowImpl obj,
                            Object value) {
                obj.setTotal((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjCuttingWorkingHoursL_VORowImpl object);

        public abstract void put(MnjCuttingWorkingHoursL_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();
    public static final int WORKINGHOURBASIC = AttributesEnum.WorkingHourBasic.index();
    public static final int MANPOWERBASIC = AttributesEnum.ManpowerBasic.index();
    public static final int WORKINGHOUROVERTIME = AttributesEnum.WorkingHourOvertime.index();
    public static final int MANPOWEROVERTIME = AttributesEnum.ManpowerOvertime.index();
    public static final int WORKINGHOUREXTRAOT1 = AttributesEnum.WorkingHourExtraot1.index();
    public static final int MANPOWEREXTRAOT1 = AttributesEnum.ManPowerExtraot1.index();
    public static final int WORKINGHOUREXTRAOT2 = AttributesEnum.WorkingHourExtraot2.index();
    public static final int MANPOWEREXTRAOT2 = AttributesEnum.ManPowerExtraot2.index();
    public static final int TOTALATTENDEDMINUTES = AttributesEnum.TotalAttendedMinutes.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int TOTAL = AttributesEnum.Total.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjCuttingWorkingHoursL_VORowImpl() {
    }

    /**
     * Gets MnjCuttingWorkingHoursL_EO entity object.
     * @return the MnjCuttingWorkingHoursL_EO
     */
    public MnjCuttingWorkingHoursL_EOImpl getMnjCuttingWorkingHoursL_EO() {
        return (MnjCuttingWorkingHoursL_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @return the ORGANIZATION_ID
     */
    public Number getOrganizationId() {
        return (Number) getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @param value value to set the ORGANIZATION_ID
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * Gets the attribute value for WORKING_HOUR_BASIC using the alias name WorkingHourBasic.
     * @return the WORKING_HOUR_BASIC
     */
    public Number getWorkingHourBasic() {
        return (Number) getAttributeInternal(WORKINGHOURBASIC);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKING_HOUR_BASIC using the alias name WorkingHourBasic.
     * @param value value to set the WORKING_HOUR_BASIC
     */
    public void setWorkingHourBasic(Number value) {
        setAttributeInternal(WORKINGHOURBASIC, value);
    }

    /**
     * Gets the attribute value for MANPOWER_BASIC using the alias name ManpowerBasic.
     * @return the MANPOWER_BASIC
     */
    public Number getManpowerBasic() {
        return (Number) getAttributeInternal(MANPOWERBASIC);
    }

    /**
     * Sets <code>value</code> as attribute value for MANPOWER_BASIC using the alias name ManpowerBasic.
     * @param value value to set the MANPOWER_BASIC
     */
    public void setManpowerBasic(Number value) {
        setAttributeInternal(MANPOWERBASIC, value);
    }

    /**
     * Gets the attribute value for WORKING_HOUR_OVERTIME using the alias name WorkingHourOvertime.
     * @return the WORKING_HOUR_OVERTIME
     */
    public Number getWorkingHourOvertime() {
        return (Number) getAttributeInternal(WORKINGHOUROVERTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKING_HOUR_OVERTIME using the alias name WorkingHourOvertime.
     * @param value value to set the WORKING_HOUR_OVERTIME
     */
    public void setWorkingHourOvertime(Number value) {
        setAttributeInternal(WORKINGHOUROVERTIME, value);
    }

    /**
     * Gets the attribute value for MANPOWER_OVERTIME using the alias name ManpowerOvertime.
     * @return the MANPOWER_OVERTIME
     */
    public Number getManpowerOvertime() {
        return (Number) getAttributeInternal(MANPOWEROVERTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for MANPOWER_OVERTIME using the alias name ManpowerOvertime.
     * @param value value to set the MANPOWER_OVERTIME
     */
    public void setManpowerOvertime(Number value) {
        setAttributeInternal(MANPOWEROVERTIME, value);
    }

    /**
     * Gets the attribute value for WORKING_HOUR_EXTRAOT_1 using the alias name WorkingHourExtraot1.
     * @return the WORKING_HOUR_EXTRAOT_1
     */
    public Number getWorkingHourExtraot1() {
        return (Number) getAttributeInternal(WORKINGHOUREXTRAOT1);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKING_HOUR_EXTRAOT_1 using the alias name WorkingHourExtraot1.
     * @param value value to set the WORKING_HOUR_EXTRAOT_1
     */
    public void setWorkingHourExtraot1(Number value) {
        setAttributeInternal(WORKINGHOUREXTRAOT1, value);
    }

    /**
     * Gets the attribute value for MAN_POWER_EXTRAOT_1 using the alias name ManPowerExtraot1.
     * @return the MAN_POWER_EXTRAOT_1
     */
    public Number getManPowerExtraot1() {
        return (Number) getAttributeInternal(MANPOWEREXTRAOT1);
    }

    /**
     * Sets <code>value</code> as attribute value for MAN_POWER_EXTRAOT_1 using the alias name ManPowerExtraot1.
     * @param value value to set the MAN_POWER_EXTRAOT_1
     */
    public void setManPowerExtraot1(Number value) {
        setAttributeInternal(MANPOWEREXTRAOT1, value);
    }

    /**
     * Gets the attribute value for WORKING_HOUR_EXTRAOT_2 using the alias name WorkingHourExtraot2.
     * @return the WORKING_HOUR_EXTRAOT_2
     */
    public Number getWorkingHourExtraot2() {
        return (Number) getAttributeInternal(WORKINGHOUREXTRAOT2);
    }

    /**
     * Sets <code>value</code> as attribute value for WORKING_HOUR_EXTRAOT_2 using the alias name WorkingHourExtraot2.
     * @param value value to set the WORKING_HOUR_EXTRAOT_2
     */
    public void setWorkingHourExtraot2(Number value) {
        setAttributeInternal(WORKINGHOUREXTRAOT2, value);
    }

    /**
     * Gets the attribute value for MAN_POWER_EXTRAOT_2 using the alias name ManPowerExtraot2.
     * @return the MAN_POWER_EXTRAOT_2
     */
    public Number getManPowerExtraot2() {
        return (Number) getAttributeInternal(MANPOWEREXTRAOT2);
    }

    /**
     * Sets <code>value</code> as attribute value for MAN_POWER_EXTRAOT_2 using the alias name ManPowerExtraot2.
     * @param value value to set the MAN_POWER_EXTRAOT_2
     */
    public void setManPowerExtraot2(Number value) {
        setAttributeInternal(MANPOWEREXTRAOT2, value);
    }

    /**
     * Gets the attribute value for TOTAL_ATTENDED_MINUTES using the alias name TotalAttendedMinutes.
     * @return the TOTAL_ATTENDED_MINUTES
     */
    public Number getTotalAttendedMinutes() {
        return (Number) getAttributeInternal(TOTALATTENDEDMINUTES);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_ATTENDED_MINUTES using the alias name TotalAttendedMinutes.
     * @param value value to set the TOTAL_ATTENDED_MINUTES
     */
    public void setTotalAttendedMinutes(Number value) {
        setAttributeInternal(TOTALATTENDEDMINUTES, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Total.
     * @return the Total
     */
    public Number getTotal() {
        return (Number) getAttributeInternal(TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Total.
     * @param value value to set the  Total
     */
    public void setTotal(Number value) {
        setAttributeInternal(TOTAL, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
