package model.Cutting_ManPower.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 12 14:47:32 PKT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCuttingWorkingHoursL_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjCuttingWorkingHoursL_VOImpl() {
    }
}
